In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
# Make outputs reproducible
np.random.seed(42)

# Nicer float display in pandas
pd.set_option("display.float_format", lambda x: f"{x:.3f}")

## Part 1 — Data Cleaning & Preprocessing

Real datasets are almost never clean. Before training any ML model we need to handle things like:

- Missing values (`NaN`)
- Duplicated rows
- Inconsistent text (capitalization, whitespace)
- Wrong data types
- Outliers
- Features on very different scales

We will build three small synthetic datasets, each designed to illustrate a specific problem.

In [7]:
# Dataset A: students with missing values
dataset_a = pd.DataFrame({
    "student_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "age":        [20, 21, np.nan, 22, 23, 20, np.nan, 24],
    "study_hours":[10, 12, 8,  np.nan, 15, 9, 11, 14],
    "score":      [78, 82, 65, 70, np.nan, 72, 80, 88],
})

dataset_a

   student_id    age  study_hours  score
0           1 20.000       10.000 78.000
1           2 21.000       12.000 82.000
2           3    NaN        8.000 65.000
3           4 22.000          NaN 70.000
4           5 23.000       15.000    NaN
5           6 20.000        9.000 72.000
6           7    NaN       11.000 80.000
7           8 24.000       14.000 88.000

In [8]:
# Step 1: detect missing values per column
print("Missing values per column:")
print(dataset_a.isna().sum())

Missing values per column:
student_id     0
age            2
study_hours    1
score          1
dtype: int64

In [9]:
# Step 2: impute (fill) missing values
# Strategy: fill numeric columns with the column mean.
# This is a simple, very common baseline strategy.

dataset_a_clean = dataset_a.copy()

for col in ["age", "study_hours", "score"]:
    mean_value = dataset_a_clean[col].mean()
    dataset_a_clean[col] = dataset_a_clean[col].fillna(mean_value)

dataset_a_clean

   student_id    age  study_hours  score
0           1 20.000       10.000 78.000
1           2 21.000       12.000 82.000
2           3 21.667        8.000 65.000
3           4 22.000       11.286 70.000
4           5 23.000       15.000 76.429
5           6 20.000        9.000 72.000
6           7 21.667       11.000 80.000
7           8 24.000       14.000 88.000