In [1]:
# Imports pandas and assign it to the variable `pd`
import pandas as pd

# We often import NumPy (numerical python) with pandas
# we will import that and assign it to the variable `np`
import numpy as np

# Load matplotlib for plotting later in the workshop
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
unemployment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [4]:
type(unemployment)

pandas.DataFrame

In [5]:
unemployment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [6]:
unemployment.shape

(20796, 5)

In [7]:
unemployment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [8]:
unemployment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [9]:
unemployment.describe()

              month  unemployment  unemployment_rate
count  20796.000000  2.079600e+04       19851.000000
mean    1999.401290  7.900818e+05           8.179764
std        7.483751  1.015280e+06           3.922533
min     1983.010000  2.000000e+03           1.100000
25%     1994.090000  1.400000e+05           5.200000
50%     2001.010000  3.100000e+05           7.600000
75%     2006.010000  1.262250e+06          10.000000
max     2010.120000  4.773000e+06          20.900000

In [10]:
my_list = ['a', 'b', 'c', 'd', 'e', 'f']

In [11]:
my_list[2:]

['c', 'd', 'e', 'f']

In [16]:
my_list[len(my_list)-4:]

['c', 'd', 'e', 'f']

# countries.csv exploration

In [20]:
df = pd.read_csv("/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/countries.csv")
df

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682
5,cz,CZ,eu,Czech Republic,République tchèque,Tschechische Republik,49.803531,15.474998
6,dk,DK,eu,Denmark,Danemark,Dänemark,55.939684,9.516689
7,ee,EE,eu,Estonia,Estonie,Estland,58.592469,25.806950
8,fi,FI,eu,Finland,Finlande,Finnland,64.950159,26.067564
9,fr,FR,eu,France,France,Frankreich,46.710994,1.718561
10,de,DE,eu,Germany (including former GDR from 1991),Allemagne (incluant l'ancienne RDA à partir de...,Deutschland (einschließlich der ehemaligen DDR...,51.163825,10.454048
11,gr,GR,eu,Greece,Grèce,Griechenland,39.698467,21.577256
12,hu,HU,eu,Hungary,Hongrie,Ungarn,47.161163,19.504265
13,ie,IE,eu,Ireland,Irlande,Irland,53.415260,-8.239122
14,it,IT,eu,Italy,Italie,Italien,42.504191,12.573787
15,lv,LV,eu,Latvia,Lettonie,Lettland,56.880117,24.606555
16,lt,LT,eu,Lithuania,Lituanie,Litauen,55.173687,23.943168
17,lu,LU,eu,Luxembourg,Luxembourg,Luxemburg,49.815319,6.133352
18,mt,MT,eu,Malta,Malte,Malta,35.902422,14.447461
19,nl,NL,eu,Netherlands,Pays-Bas,Niederlande,52.108118,5.330198
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.556460,12.665766
21,pl,PL,eu,Poland,Pologne,Polen,51.918907,19.134334
22,pt,PT,eu,Portugal,Portugal,Portugal,39.558069,-7.844941
23,ro,RO,eu,Romania,Roumanie,Rumänien,45.942611,24.990152
24,sk,SK,eu,Slovakia,Slovaquie,Slowakei,48.672644,19.700032
25,si,SI,eu,Slovenia,Slovénie,Slowenien,46.149259,14.986617
26,es,ES,eu,Spain,Espagne,Spanien,39.895013,-2.988296
27,se,SE,eu,Sweden,Suède,Schweden,62.198467,14.896307
28,tr,TR,non-eu,Turkey,Turquie,Türkei,38.952942,35.439795
29,uk,GB,eu,United Kingdom,Royaume-Uni,Vereinigtes Königreich,54.315447,-2.232612

In [21]:
df.loc[3, 'google_country_code']

'HR'

In [22]:
df.loc[:4,:]

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682

In [24]:
df.iloc[:,:4]

,country,google_country_code,country_group,name_en
0,at,AT,eu,Austria
1,be,BE,eu,Belgium
2,bg,BG,eu,Bulgaria
3,hr,HR,non-eu,Croatia
4,cy,CY,eu,Cyprus
5,cz,CZ,eu,Czech Republic
6,dk,DK,eu,Denmark
7,ee,EE,eu,Estonia
8,fi,FI,eu,Finland
9,fr,FR,eu,France
10,de,DE,eu,Germany (including former GDR from 1991)
11,gr,GR,eu,Greece
12,hu,HU,eu,Hungary
13,ie,IE,eu,Ireland
14,it,IT,eu,Italy
15,lv,LV,eu,Latvia
16,lt,LT,eu,Lithuania
17,lu,LU,eu,Luxembourg
18,mt,MT,eu,Malta
19,nl,NL,eu,Netherlands
20,no,NO,non-eu,Norway
21,pl,PL,eu,Poland
22,pt,PT,eu,Portugal
23,ro,RO,eu,Romania
24,sk,SK,eu,Slovakia
25,si,SI,eu,Slovenia
26,es,ES,eu,Spain
27,se,SE,eu,Sweden
28,tr,TR,non-eu,Turkey
29,uk,GB,eu,United Kingdom

In [26]:
test = df.loc[20:25, :]
test

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.556460,12.665766
21,pl,PL,eu,Poland,Pologne,Polen,51.918907,19.134334
22,pt,PT,eu,Portugal,Portugal,Portugal,39.558069,-7.844941
23,ro,RO,eu,Romania,Roumanie,Rumänien,45.942611,24.990152
24,sk,SK,eu,Slovakia,Slovaquie,Slowakei,48.672644,19.700032
25,si,SI,eu,Slovenia,Slovénie,Slowenien,46.149259,14.986617

In [31]:
test[test['country_group']== 'non-eu']

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.55646,12.665766

In [32]:
df[df['longitude']>25]

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682
7,ee,EE,eu,Estonia,Estonie,Estland,58.592469,25.806950
8,fi,FI,eu,Finland,Finlande,Finnland,64.950159,26.067564
28,tr,TR,non-eu,Turkey,Turquie,Türkei,38.952942,35.439795