# Creating virtual envieorment  
1  uv venv mienv
2  source mienv/bin/activate
3  uv pip install ipykernel
4  python -m ipykernel install --user --name=mienv

In [2]:
!curl -LsSf https://astral.sh/uv/install.sh | sh

downloading uv 0.11.1 x86_64-unknown-linux-gnu
installing to /home/codespace/.local/bin
  uv
  uvx
everything's installed!

In [3]:
!uv self update

info: Checking for updates...
success: You're already on version v0.11.1 of uv (the latest version).

In [3]:
!uv pip install numpy 
!uv pip install pandas

Using Python 3.12.1 environment at: mienv
Checked 1 package in 1ms

Using Python 3.12.1 environment at: mienv
Checked 1 package in 2ms

In [1]:
import numpy as np 
import pandas as pd

In [2]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
date = pd.date_range("20260102",periods=6)
date

DatetimeIndex(['2026-01-02', '2026-01-03', '2026-01-04', '2026-01-05',
               '2026-01-06', '2026-01-07'],
              dtype='datetime64[us]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6,4), index=date, columns=list("ABCD"))
df

                   A         B         C         D
2026-01-02  0.500439  0.105732  2.281521  0.144040
2026-01-03 -0.608967 -0.709028 -1.188711  0.005116
2026-01-04  0.181438 -0.408411  0.850848 -0.901493
2026-01-05  0.480485  2.613921 -0.015315 -0.907316
2026-01-06 -0.625142  1.712277  1.461696  2.428322
2026-01-07 -1.024698  0.809377 -0.403269 -0.562678

In [5]:
df2 = pd.DataFrame(
    {
        "A":1.0, 
        "B":pd.Timestamp("20260306"),
        "C":pd.Series(1, index=list(range(4)), dtype="float32"),
        "D":np.array([3]*4,dtype="int32"),
        "E":pd.Categorical(["test","train","test","train"]),
        "F":"foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2026-03-06  1.0  3   test  foo
1  1.0 2026-03-06  1.0  3  train  foo
2  1.0 2026-03-06  1.0  3   test  foo
3  1.0 2026-03-06  1.0  3  train  foo

In [6]:
df.head()

                   A         B         C         D
2026-01-02  0.500439  0.105732  2.281521  0.144040
2026-01-03 -0.608967 -0.709028 -1.188711  0.005116
2026-01-04  0.181438 -0.408411  0.850848 -0.901493
2026-01-05  0.480485  2.613921 -0.015315 -0.907316
2026-01-06 -0.625142  1.712277  1.461696  2.428322

In [7]:
df.tail(3)

                   A         B         C         D
2026-01-05  0.480485  2.613921 -0.015315 -0.907316
2026-01-06 -0.625142  1.712277  1.461696  2.428322
2026-01-07 -1.024698  0.809377 -0.403269 -0.562678